"""empty message

Revision ID: 6bca0acc9e9a
Revises: 
Create Date: 2017-03-09 16:44:38.562812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bca0acc9e9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('user_profile', sa.Column('image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'image')
    op.drop_column('user_profile', 'created_on')
    # ### end Alembic commands ###
